language: ruby

sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - 2.3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

install: bundle install --path=vendor/bundle --retry=3 --jobs=3

before_script:
  - cp db/config.travis.yml db/config.yml

script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

addons:
  code_climate:
    repo_token: 79db524674654c4815f1923c6d5384922226942410c2fa25c5e5cbf9f3f7b372
